# Generated by Django 5.2.17 on 2026-08-18 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_historicalusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalusuario',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='historicalusuario',
            name='password',
        ),
    ]
